console.log("ISRAEL");
var myName="mayan elias"
console.log(myName);
var myNumber= 50;
console.log(myNumber);
var myNumberFiveTimes= Array(5).fill(2);
console.log(myNumberFiveTimes);
var myNumberOne= 10;
var myNumberTwo= 20;
var myNumberThree= 30;
var myNumberFour= 40;
var avgNumber= (myNumberOne+myNumberTwo+myNumberThree+myNumberFour)/4;
var sumNumber= myNumberOne+myNumberTwo+myNumberThree+myNumberFour;
console.log(avgNumber);
console.log(sumNumber);
var lengthRectangle= 20;
var wideReactangle= 30;
var sumReactangleArea=(lengthRectangle*wideReactangle);
console.log(sumReactangleArea);
var num1=1;
var num2=2;
console.log(num1,num2)
if(num1){
console.log(num1+1);
}
if(num2){
    console.log(num2-1);
}











alert("it works")


